env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: 'tsconfig.json'
  tsconfigRootDir: './'

plugins:
  - react
ignorePatterns:
  - src/reportWebVitals.ts
  - src/react-app-env.d.ts
  - setupTests.ts
rules: 
  semi: [2, "always"]
  "@typescript-eslint/semi": [0]
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/space-before-function-paren": "off"
  "@typescript-eslint/quotes": "off"
  "@typescript-eslint/no-misused-promises": 
  - error
  - checksVoidReturn: false
  "no-multi-str": "off"