env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: 'tsconfig.json'
  tsconfigRootDir: './'

plugins:
  - react
rules: 
  semi: [2, "always"]
  "@typescript-eslint/semi": [0]

